version: 2.1

default_version: &default_version 1.8.2

jobs:
  build:
    parameters:
      version:
        description: Elixir Version
        type: string
        default: *default_version

    parallelism: 1
    docker:
      - image: elixir:<< parameters.version >>

    working_directory: ~/app

    steps:
      - checkout  # check out source code to working directory
      - run: wget https://github.com/nats-io/gnatsd/releases/download/v1.4.1/gnatsd-v1.4.1-linux-amd64.zip
      - run: unzip gnatsd-v1.4.1-linux-amd64.zip
      - run:
          command: ./gnatsd-v1.4.1-linux-amd64/gnatsd
          background: true
      - run:
          command: ./gnatsd-v1.4.1-linux-amd64/gnatsd -p 4223 --user bob --pass alice
          background: true
      - run:
          command: ./gnatsd-v1.4.1-linux-amd64/gnatsd -p 4224 --tls --tlscert test/fixtures/server.pem --tlskey test/fixtures/key.pem
          background: true
      - run:
          command: ./gnatsd-v1.4.1-linux-amd64/gnatsd -p 4225 --tls --tlscert test/fixtures/server.pem --tlskey test/fixtures/key.pem --tlscacert test/fixtures/ca.pem --tlsverify
          background: true
      - run:
          command: ./gnatsd-v1.4.1-linux-amd64/gnatsd -p 4226 --auth SpecialToken
          background: true
      - restore_cache:
          keys:
            - build-<<parameters.version>>
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: MIX_ENV=test mix do deps.get, compile
      - save_cache:
          key: build-<<parameters.version>>
          paths:
          - "deps"
          - "_build"
          - "~/.mix"
      - run: mix test --include multi_server
      - run: N=400 mix test --only property
  lint:
    parameters:
      version:
        description: Elixir Version
        type: string
        default: *default_version

    parallelism: 1
    docker:
      - image: elixir:<< parameters.version >>

    working_directory: ~/app

    steps:
      - checkout  # check out source code to working directory
      - restore_cache:
          keys:
            - lint-<<parameters.version>>-{{ checksum "mix.lock" }}
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, compile
      - run: mix format --check-formatted
      - run: mix dialyzer --halt-exit-status
      - save_cache:
          key: lint-<<parameters.version>>-{{ checksum "mix.lock" }}
          paths:
          - "deps"
          - "_build"
          - "~/.mix"

workflows:
  version: 2.1
  testing_all_versions:
    jobs:
      - build:
          name: "Test Elixir 1.9.1"
          version: 1.9.1 
      - build:
          name: "Test Elixir 1.8.2"
          version: 1.8.2 
      - build:
          name: "Test Elixir 1.7.4"
          version: 1.7.4
      - build:
          name: "Test Elixir 1.6.6"
          version: 1.6.6
      - lint:
          name: "Check formatting and Types"