version: 2.1

default_version: &default_version 1.13.1

jobs:
  build:
    parameters:
      version:
        description: Elixir Version
        type: string
        default: *default_version

    parallelism: 1
    docker:
      - image: elixir:<< parameters.version >>

    working_directory: ~/app

    steps:
      - checkout  # check out source code to working directory
      - run: wget https://github.com/nats-io/nats-server/releases/download/v2.6.6/nats-server-v2.6.6-linux-amd64.zip
      - run: unzip nats-server-v2.6.6-linux-amd64.zip
      - run:
          command: ./nats-server-v2.6.6-linux-amd64/nats-server
          background: true
      - run:
          command: ./nats-server-v2.6.6-linux-amd64/nats-server -p 4223 --user bob --pass alice
          background: true
      - run:
          command: ./nats-server-v2.6.6-linux-amd64/nats-server -p 4224 --tls --tlscert test/fixtures/server-cert.pem --tlskey test/fixtures/server-key.pem
          background: true
      - run:
          command: ./nats-server-v2.6.6-linux-amd64/nats-server -p 4225 --tls --tlscert test/fixtures/server-cert.pem --tlskey test/fixtures/server-key.pem --tlscacert test/fixtures/ca.pem --tlsverify
          background: true
      - run:
          command: ./nats-server-v2.6.6-linux-amd64/nats-server -p 4226 --auth SpecialToken
          background: true
      - run:
          command: ./nats-server-v2.6.6-linux-amd64/nats-server -p 4227 -c test/fixtures/nkey_config
          background: true
      - restore_cache:
          keys:
            - build-<<parameters.version>>
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: MIX_ENV=test mix do deps.get, compile
      - save_cache:
          key: build-<<parameters.version>>
          paths:
          - "deps"
          - "_build"
          - "~/.mix"
      - run: mix test --include multi_server --exclude ci_skip
      - run: N=400 mix test --only property
  lint:
    parameters:
      version:
        description: Elixir Version
        type: string
        default: *default_version

    parallelism: 1
    docker:
      - image: elixir:<< parameters.version >>

    working_directory: ~/app

    steps:
      - checkout  # check out source code to working directory
      - restore_cache:
          keys:
            - lint-<<parameters.version>>-{{ checksum "mix.lock" }}
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, compile
      - run: mix format --check-formatted
      - run: mix dialyzer
      - save_cache:
          key: lint-<<parameters.version>>-{{ checksum "mix.lock" }}
          paths:
          - "deps"
          - "_build"
          - "~/.mix"

workflows:
  version: 2.1
  testing_all_versions:
    jobs:
      - build:
          name: "Test Elixir 1.13.1"
          version: 1.13.1
      - build:
          name: "Test Elixir 1.12.3"
          version: 1.12.3
      - build:
          name: "Test Elixir 1.11.4"
          version: 1.11.4
      - build:
          name: "Test Elixir 1.10.4"
          version: 1.10.4
      - build:
          name: "Test Elixir 1.9.4"
          version: 1.9.4
      - build:
          name: "Test Elixir 1.8.2"
          version: 1.8.2
      - build:
          name: "Test Elixir 1.7.4"
          version: 1.7.4
      - lint:
          name: "Check formatting and Types"